// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CopyrightDiv: typeof import('./src/components/CopyrightDiv.vue')['default']
    Initiator: typeof import('./src/components/Initiator.vue')['default']
    InputArea: typeof import('./src/components/InputArea.vue')['default']
    NDivider: typeof import('naive-ui')['NDivider']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NSpace: typeof import('naive-ui')['NSpace']
    RequirementBlock: typeof import('./src/components/RequirementBlock.vue')['default']
    RequirementParser: typeof import('./src/components/RequirementParser.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StuffParser: typeof import('./src/components/StuffParser.vue')['default']
  }
}
